apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_NAME: cG9zdGdyZXMK # postgres
  POSTGRES_USER: cG9zdGdyZXMK # postgres
  POSTGRES_PASSWORD: bmV3cGFzc3dvcmQ= # newpassword